server:
  port: 9050

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dancesfly/MMBConfigData
          searchPaths: data